import { Geist, Geist_Mono } from "next/font/google";
import { Qwitcher_Grypen } from 'next/font/google';
import "./globals.css";

const qwitcher = Qwitcher_Grypen({
  weight: ['400', '700'], // Choose the weights you need
  subsets: ['latin'],
  variable: '--font-qwitcher', // This creates a CSS variable
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
      {children}</body>
    </html >
  );
}
